# Generated by Django 4.0.5 on 2022-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreation',
            new_name='timeAdding',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dateCreation',
            new_name='timeAdding',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='categoryLink',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='postLink',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryType',
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
